[package]
name = "resolvelink"
version = "0.1.0"
authors = ["Linus Heckemann <git@sphalerite.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "resolvelink"
path = "resolvelink.rs"
